### ISSUE TITLE
Hey, I'm Trying to build a similar project. Thanks for this

### ISSUE THREAD

**Issue by U-C-S** [hfedcba/SaPhoTeKeyboard#1]
Though, I don't know whether my project is feasible or not. My Native Language is Telugu.

I see you aren't a native or either a Indian, So, Any specific reason why you chose Telugu? Just Curious

😅Sorry for creating a new issue

**Comment by hfedcba** [comment]
I was in Andhra Pradesh at the time I wrote this ;-).
